# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_kuznetsov', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='rating',
            new_name='rating_dislike',
        ),
        migrations.AddField(
            model_name='question',
            name='rating_like',
            field=models.IntegerField(default=0),
        ),
    ]
