# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_kuznetsov', '0002_auto_20180918_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_like', models.IntegerField(default=0)),
                ('rating_dislike', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LikesQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_like', models.IntegerField(default=0)),
                ('rating_dislike', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_kuznetsov.Profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_kuznetsov.Question')),
            ],
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='rating',
            new_name='rating_dislike',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likesanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_kuznetsov.Answer'),
        ),
        migrations.AddField(
            model_name='likesanswer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_kuznetsov.Profile'),
        ),
        migrations.AddField(
            model_name='likesanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_kuznetsov.Question'),
        ),
    ]
