# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 12:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ask_kuznetsov', '0004_auto_20180923_1520'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='likesquestion',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
