# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask_kuznetsov', '0005_auto_20180924_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(-1, b'dislike'), (1, b'like')], verbose_name=b'Vote')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='likesanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='likesanswer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likesanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='likesquestion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likesquestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='LikesAnswer',
        ),
        migrations.DeleteModel(
            name='LikesQuestion',
        ),
    ]
