# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=b'avatars/no-frame.png', null=True, upload_to=b'avatars'),
        ),
    ]
